// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MomsKitchen.DATA;

namespace MomsKitchen.DATA.Migrations
{
    [DbContext(typeof(Model))]
    [Migration("20210706141344_initial-create00")]
    partial class initialcreate00
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("RoleId");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "69a4116d-b1bd-4f0b-b6a7-a13bb5eb639f",
                            ConcurrencyStamp = "738d3523-d662-4078-879a-0f1c9dd8371a",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = "a1897ddf-24d5-43cb-af30-1e8425003eae",
                            ConcurrencyStamp = "197060b1-8b67-4307-adc1-87dd4a7b4684",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2e275270-0e64-4926-905e-70a2fab92006",
                            ConcurrencyStamp = "1d62cdef-763e-45ba-b8a2-d5911e0b4a1a",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleClaimId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UserId");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserClaimId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "cd75a482-cac0-45f2-9c20-bae54f363742",
                            RoleId = "69a4116d-b1bd-4f0b-b6a7-a13bb5eb639f"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("MomsKitchen.DATA.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActivityUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ActivityUpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MomsKitchen.DATA.Entities.ComplexityLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActivityUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ActivityUpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ComplexityWeight")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ComplexityLevels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9579ec34-7b18-43d5-8726-0faf1cb97d03"),
                            ActivityUpdatedAt = new DateTime(2021, 7, 6, 16, 13, 44, 92, DateTimeKind.Local).AddTicks(6442),
                            ActivityUpdatedBy = new Guid("cd75a482-cac0-45f2-9c20-bae54f363742"),
                            ComplexityWeight = 1,
                            CreatedAt = new DateTime(2021, 7, 6, 16, 13, 44, 92, DateTimeKind.Local).AddTicks(5766),
                            CreatedBy = new Guid("cd75a482-cac0-45f2-9c20-bae54f363742"),
                            Description = "Meals that can be made with minimal effort.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Low",
                            UpdatedAt = new DateTime(2021, 7, 6, 16, 13, 44, 92, DateTimeKind.Local).AddTicks(6137),
                            UpdatedBy = new Guid("cd75a482-cac0-45f2-9c20-bae54f363742")
                        },
                        new
                        {
                            Id = new Guid("77e8cefa-b520-48aa-9347-761fcad33252"),
                            ActivityUpdatedAt = new DateTime(2021, 7, 6, 16, 13, 44, 92, DateTimeKind.Local).AddTicks(8066),
                            ActivityUpdatedBy = new Guid("cd75a482-cac0-45f2-9c20-bae54f363742"),
                            ComplexityWeight = 2,
                            CreatedAt = new DateTime(2021, 7, 6, 16, 13, 44, 92, DateTimeKind.Local).AddTicks(8050),
                            CreatedBy = new Guid("cd75a482-cac0-45f2-9c20-bae54f363742"),
                            Description = "Meals that require effort.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Normal",
                            UpdatedAt = new DateTime(2021, 7, 6, 16, 13, 44, 92, DateTimeKind.Local).AddTicks(8062),
                            UpdatedBy = new Guid("cd75a482-cac0-45f2-9c20-bae54f363742")
                        },
                        new
                        {
                            Id = new Guid("3f6e86b6-7d3e-4a75-a1f1-58b30aebcba3"),
                            ActivityUpdatedAt = new DateTime(2021, 7, 6, 16, 13, 44, 92, DateTimeKind.Local).AddTicks(8089),
                            ActivityUpdatedBy = new Guid("cd75a482-cac0-45f2-9c20-bae54f363742"),
                            ComplexityWeight = 3,
                            CreatedAt = new DateTime(2021, 7, 6, 16, 13, 44, 92, DateTimeKind.Local).AddTicks(8083),
                            CreatedBy = new Guid("cd75a482-cac0-45f2-9c20-bae54f363742"),
                            Description = "Meals that require extra cooking knowledge.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Complex",
                            UpdatedAt = new DateTime(2021, 7, 6, 16, 13, 44, 92, DateTimeKind.Local).AddTicks(8086),
                            UpdatedBy = new Guid("cd75a482-cac0-45f2-9c20-bae54f363742")
                        },
                        new
                        {
                            Id = new Guid("3aec7e7b-24df-4964-8e44-5f52cfc39ec3"),
                            ActivityUpdatedAt = new DateTime(2021, 7, 6, 16, 13, 44, 92, DateTimeKind.Local).AddTicks(8103),
                            ActivityUpdatedBy = new Guid("cd75a482-cac0-45f2-9c20-bae54f363742"),
                            ComplexityWeight = 4,
                            CreatedAt = new DateTime(2021, 7, 6, 16, 13, 44, 92, DateTimeKind.Local).AddTicks(8098),
                            CreatedBy = new Guid("cd75a482-cac0-45f2-9c20-bae54f363742"),
                            Description = "Meals that require special cooking skills.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "VeryComplex",
                            UpdatedAt = new DateTime(2021, 7, 6, 16, 13, 44, 92, DateTimeKind.Local).AddTicks(8100),
                            UpdatedBy = new Guid("cd75a482-cac0-45f2-9c20-bae54f363742")
                        });
                });

            modelBuilder.Entity("MomsKitchen.DATA.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActivityUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ActivityUpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComplexityLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ComplexityLevelId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("MomsKitchen.DATA.Entities.RecipeCategory", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RecipeId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("RecipeCategories");
                });

            modelBuilder.Entity("MomsKitchen.DATA.Entities.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateTime>("ActivityUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ActivityUpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "cd75a482-cac0-45f2-9c20-bae54f363742",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fc1c805f-16e9-4d89-a62b-8feddc268c48",
                            Email = "superadmin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERADMIN@GMAIL.COM",
                            NormalizedUserName = "SUPERADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEHC/ZED7eBb+Ggtlvm2H4LMK1hN9aVCahX7koginK5g3sb2Ph6rm+O7Q0TJQJK7qsA==",
                            PhoneNumber = "+385915007122",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "adfed03a-5aea-496f-a783-8602022d2aae",
                            TwoFactorEnabled = true,
                            UserName = "superadmin",
                            ActivityUpdatedAt = new DateTime(2021, 7, 6, 16, 13, 44, 75, DateTimeKind.Local).AddTicks(4930),
                            ActivityUpdatedBy = new Guid("cd75a482-cac0-45f2-9c20-bae54f363742"),
                            CreatedAt = new DateTime(2021, 7, 6, 16, 13, 44, 71, DateTimeKind.Local).AddTicks(7891),
                            CreatedBy = new Guid("cd75a482-cac0-45f2-9c20-bae54f363742"),
                            FirstName = "Super",
                            IsActive = true,
                            LastName = "Admin",
                            UpdatedAt = new DateTime(2021, 7, 6, 16, 13, 44, 75, DateTimeKind.Local).AddTicks(4421),
                            UpdatedBy = new Guid("cd75a482-cac0-45f2-9c20-bae54f363742")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MomsKitchen.DATA.Entities.Recipe", b =>
                {
                    b.HasOne("MomsKitchen.DATA.Entities.ComplexityLevel", "ComplexityLevel")
                        .WithMany("Recipes")
                        .HasForeignKey("ComplexityLevelId");

                    b.Navigation("ComplexityLevel");
                });

            modelBuilder.Entity("MomsKitchen.DATA.Entities.RecipeCategory", b =>
                {
                    b.HasOne("MomsKitchen.DATA.Entities.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MomsKitchen.DATA.Entities.Recipe", "Recipe")
                        .WithMany("Categories")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MomsKitchen.DATA.Entities.Category", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("MomsKitchen.DATA.Entities.ComplexityLevel", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("MomsKitchen.DATA.Entities.Recipe", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
